- system/shadowdark.mjs
- system/src/documents/__tests__/documents-actor.test.mjs
- system/src/documents/__tests__/documents-item.test.mjs
- system/src/testing/index.mjs
- system/src/testing/testUtils.mjs
I've written tests similar to Old-School Essentials here, utilizing the Quench module. (https://github.com/Ethaks/FVTT-Quench).
If this type of testing is relevant, I'd gladly spend more time writing tests for Shadowdark too.
Added tests for `Actor` documents, and `Item` documents.
> feat(testing): Initial tests

- system/src/documents/__tests__/documents-actor.test.mjs
- system/src/documents/__tests__/documents-item.test.mjs
- system/src/sheets/__tests__/sheets-actor.test.mjs
- system/src/testing/testUtils.mjs
Added tests for added features on `Actor` documents:
- `attackBonus(attackType)`
- `updateArmor(updatedItem)`
- `updateArmorClass()`
Added tests for `Item` documents:
- Tests to create all item types
- `hasProperty(property)`
- `isAShield()`
- `isNotAShield()`
Added cleanup for  tests for `ActorSheet`.
> chore(test): more document tests

- i18n/en.yaml
- system/src/documents/ActorSD.mjs
- system/src/documents/ItemSD.mjs
- system/src/documents/__tests__/documents-item-spell.test.mjs
- system/src/sheets/ActorSheetSD.mjs
- system/src/sheets/__tests__/sheets-actor.test.mjs
- system/src/testing/index.mjs
- system/templates/dialog/roll-spell-dialog.hbs
Added:
- Rolling spells, including showing the DC in the chat card
Modified:
- Refactored the previous rolling methods to be aligned in how to use bonuses & parts
Linting:
- Fixes linting message with `actorData` not being used in `sheets-actor.test.js`
> feat(spells): Spell rolling incl. spell DC

- i18n/en.yaml
- system/src/apps/TalentTypesSD.mjs
- system/src/config.mjs
Added another choice that creates an empty custom talent. Still needs a unique name so it doesn't get hidden if Custom Talent is deselected from the Talent Type choice.
> feat(talent): Custom talent choice

- system/src/documents/ItemSD.mjs
Spells got lost if the roll dialog was closed, this fixes this so that it only checks for the lost automation if the spell was actually rolled.
> fix(spell): No longer lost when close dialog

- scss/base/_chat.scss
- system/templates/chat/item-card.hbs
Reworked the Item Chatcard a bit, so that versatile weapon damage rolls are shown next to eachother:
Whereas if it is not versatile it shows as:
Also made the properties be shown in "pills" instead of a "pipe-separated" row.
> fix(css): Chatcard styling

- system/src/dice/RollSD.mjs
- system/src/documents/ActorSD.mjs
- system/templates/items/partials/npc-attack.hbs
This fixes:
- Ability scores not rollable from NPC sheet
- Template used wrong data path for `numDice` on damage rolls for NPC attacks.
> fix(npc): sheet fixes

- system/src/documents/ActorSD.mjs
Resolves #163 
The comment in #163 makes sense that we maybe shouldn't override the default settings from foundry. I don't know if we should merge this PR, but I commented away the part where this causes the override.
> fix(token): Default token disp. #163

- system/src/documents/ActorSD.mjs
The damage bonus on the `buildWeaponDisplays` function was never accounted for.
> fix(display): Weapon: damage bonus

- i18n/fi.yaml
Updated Finnish translations for 1.0.1
"AC" and "HP" are quite a bit longer and I noticed the Swedish translations kept these in. I think it might be fine to use them if this breaks any layouts.
> Updated Finnish translations for 1.0.1

- system/src/apps/ActiveEffectsSD.mjs
When a custom effect was renamed, it caused an error that prevented the selector app to open. This fixes that.
> fix(ae): Custom talents prevented app display

- system/src/apps/__tests__/apps-lightsource-tracker.test.mjs
- system/src/dice/__tests__/dice-chat-templates.test.mjs
- Cleans up the linting errors from chatcard testing.
- Adds initial test suite for Lightsource Tracker.
> chore(test): Cleanup & Lightsource tracker testing

- RELEASE_NOTES.md
- i18n/en.yaml
- system/src/tours/ShadowdarkTourLightsourceTracker.mjs
I couldn't set the settings temporary for enabling the lightsource tracker as it requires a reload. So I did the next best thing, I put a notification and show the system settings to enable it.
resolves #221
> fix: #221 Tour Settings

- RELEASE_NOTES.md
- system/src/apps/__tests__/apps-lightsource-tracker.test.mjs
- system/src/apps/__tests__/e2e-apps-lightsource-tracker.test.mjs
- system/src/testing/index.mjs
- system/src/testing/testUtils.mjs
Adds E2E tests for the Lightsource Tracker. Probably can improve this quite a lot in the future, but should give us some more coverage at least.
> chore(test): Lightsource Tracker

- system/src/tours/ShadowdarkTourPlayerRolling.mjs
Adds a step to the rolling tour about restoring spells if miscast.
> feat(tour): Spell restore

- RELEASE_NOTES.md
- i18n/en.yaml
- scss/apps/_index.scss
- scss/apps/_shadowdarkling-importer.scss
- system/src/apps/ShadowdarklingImporterSD.mjs
- system/templates/apps/shadowdarkling-importer.hbs
Adds a button to open the Shadowdarklings.net site in an iframe, which allows easy copy-json-to-clipboard at least for Firefox users.
> feat(importer): Importer improvements

- i18n/en.yaml
- i18n/fi.yaml
- system/src/apps/LightSourceTrackerSD.mjs
- system/src/apps/RealTimeSD.mjs
- system/src/apps/__tests__/apps-lightsource-tracker.test.mjs
- system/src/apps/__tests__/e2e-apps-lightsource-tracker.test.mjs
- system/src/handlebars.mjs
- system/src/hooks/light-source-tracker.mjs
- system/src/settings.mjs
- system/templates/apps/light-tracker.hbs
This adds support for using different time and calendar modules for tracking time in the campaign, and integrating that with torches. Allows for example to use SimpleCalendar module to move time forward when the party is spending extra time searching a room.
By default behavior is unchanged, but with a new option real time tracking can be disabled in cases where GM wants to use clock from another module.
Also changed the inventory and light tracker use same rounding for the time remaining.
> Implement light tracking using world time

- RELEASE_NOTES.md
- system/src/apps/__tests__/apps-shadowdarkling-importer.test.mjs
resolves #322
Updated the tests for Shadowdarkling to check that the expected cost of basic items work. It also updates the cost of `Flask or Bottle` to 3 _gp_ instead of _sp_.
> fix(test): Shadowdarkling cost test for basic item

- system/src/chat/hooks.mjs
- system/src/dice/RollSD.mjs
- system/templates/chat/item-card.hbs
- system/templates/chat/roll-d20-card.hbs
resolves #359
This could act as a short-term fix for rolls not being blinded properly. As mentioned on discord, I think we need to review and cleanup the technicals behind chat cards, but I suggest having that in a later release.
> fix(chat): Blinding of rolls

- system/packs/__tests__/fixture/basic-gear.json
- system/packs/__tests__/item.jest.test.js
With the lightsource items for Light Spell using IDs to trigger the source if dropped onto an actor, we need CI tests to make sure the IDs are not changing by mistake.
> feat(ci): Tests for Light basic items

- system/src/apps/__tests__/apps-lightsource-tracker.test.mjs
- system/src/documents/__tests__/documents-item-spell.test.mjs
- system/src/sheets/ActorSheetSD.mjs
This fixes the behavior of deleting items that is not a light source (NPC Attack for example) from an actor.
Also cleans up the failing tests due to recent updates!
> fix: Actor delete non-lightsource fix

- RELEASE_NOTES.md
- i18n/en.yaml
- system/assets/mappings/map-predefined-effects.json
- system/src/dice/RollSD.mjs
- system/src/dice/__tests__/dice.test.mjs
- system/src/documents/ActorSD.mjs
- system/src/documents/__tests__/documents-item-effect-predefined-effects.test.mjs
- system/template.json
resolves #380 
This feature will check for the maximum between the actors `bonuses.damageMultiplier` and the items. The idea is that this should support items like Potion of Giant Strength on a limited basis (multiplies damage for a certain amount of turns), as well as potential weapons having a permanent damage multiplier.
> feat: Damage Multiplier effect

- RELEASE_NOTES.md
- i18n/en.yaml
- scss/base/_dialog.scss
- system/src/apps/LightSourceTrackerSD.mjs
- system/src/hooks/drop-lightsource-on-scene.mjs
- system/src/sheets/LightSheetSD.mjs
- system/src/sheets/PlayerSheetSD.mjs
- system/templates/chat/lightsource-drop.hbs
- system/templates/dialog/assign-picked-up-lightsource.hbs
resolves #396
resolves #395
Adds a dialog for the GM to select what assigned actor should pick up the torch. It only looks for active users and their assigned characters for this.
Also fixes a bug where light sources that were dropped from the item sidebar was ignored due to the changes to dropping light sources between characters.
> fix: Dropped torches remaining unlit & allowing GM to pick up light sources for users

- system/src/documents/ActorSD.mjs
- system/templates/chat/item-card.hbs
Provide both the ability name and description. Should address #320 
There's space for improvements. Such as not revealing that nature of the effect until an actual hit. But that's a thing for a future revision.
Sample screen for Gelatinous Cube
Source: 
Updated chat output:
> Monster attack evolved

- RELEASE_NOTES.md
- i18n/en.yaml
- scss/sheets/actors/_player.scss
- system/src/sheets/ActorSheetSD.mjs
- system/src/templates.mjs
- system/templates/actors/player/abilities.hbs
- system/templates/actors/player/abilities/initiative.hbs
This address issue #311. Uses existing primitives on the `Actor` object connected to the open sheet.
- It's been placed at the bottom left. Seems to fit within default sizes
- It's configured to both "add combatant" and "update initiative" when used. Shadowdark has pretty loos rules around Initiative, defaulting to one roll per session, so this seems pretty reasonable.
One additional translation required.
Sample screenshot below.
> Add initiative to the PC sheet

- system/system.json
This PR corrects the name the Finnish language in `system.json` to be grammatically correct.
> Fix the name of the Finnish language

- RELEASE_NOTES.md
- system/src/documents/ActorSD.mjs
The dialog form was collecting manual inputs for _itemBonuses_, but _@itemBonus_ was only added for consideration during rolling if _item.system.bonuses.attackBonus_ was set.
Similar to @talentBonus, adding @itembonus to all rolls corrects the issue and is ignored if 0.
> Fixed #573

- .vscode/settings.json
- system/src/sheets/PlayerSheetSD.mjs
- system/templates/actors/player/spells.hbs
- system/templates/apps/light-tracker.hbs
My proposed UI improvement (#578)
> Standardize Spellcasting Icons

- system/src/apps/MonsterImporterSD.mjs
Fixes  #583. I tested a mass import of the entire rulebook, and with this fix, the Monster Importer now works on every monster in the core rulebook.
> fix error parsing +X weapon attacks with monsterImporter

- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/ko.yaml
- i18n/sv.yaml
- package-lock.json
- system/shadowdark.mjs
- system/src/documents/EncounterSD.mjs
- system/src/documents/_module.mjs
- system/src/settings.mjs
This creates a setting to enable "clockwise initiative" as described on page 83 of the core rulebook. Rather than all characters acting in descending order of their initiative rolls, the combatant with the highest roll goes first, then all other combatants follow in a fixed order (as though they were sitting around a table, going clockwise). The order is determined by the order of users in the User Configuration menu. All NPCs will act on the "GM's turn," going in descending order of initiative bonus.
By default, this option is disabled, as players will likely expect initiative to work the way it does in other Foundry systems, even though technically this is the way Shadowdark is played RAW.
In order to implement this setting, I had to replace the core Combat class with a new EncounterSD …
> Implement option for Clockwise Initiative

- system/src/apps/MonsterImporterSD.mjs
Addresses #616. More thoroughly and methodically sorts through the stat block of each spell to find the range.
First checks if there is a range listed before the spell DC (which is not always the case, frustratingly).
Then checks if the string "in [range]" is present to account for expressions like "an enemy within near" or "all enemies in near." It's important to check this first because some spells call out "a near-sized cube within far," which should show as far instead of near.
Then checks to find the earliest occurrence of a range word with punctuation.
I've tested this on every published monster (rulebook, Cursed Scrolls, and Monster Monday), and it seems to behave as expected. I've attached the results of the rulebook.
[npc spell …
> Make monster importer range parsing more thorough and accurate

- system/src/apps/MonsterImporterSD.mjs
Addresses #622. All I had to do was create a new object for attackObj.system.damage in the static damage case (the "else"). @PrototypeESBU, is there any reason you can see this wouldn't work? I've tested this code with every monster in the rulebook and didn't get any errors.
```
Fairy
Miniature fey folk with fluttering moth or butterfly wings.
AC 13, HP 4, ATK 1 needle +3 (1 + poison), MV near (fly), S -2, D +3, C +0, I +1, W +0, Ch +1, AL N, LV 1
Poison. DC 12 CON or fall into deep sleep for 1d4 hours.
```
Becomes
> Allow monster importer to handle static (non-dice-roll) damage

- README.md
- system/src/documents/ActorSD.mjs
- system/src/sheets/PlayerSheetSD.mjs
Fixes #715.
Learned spells now show the original spell's icon (if the scroll was created after this commit). If not, it shows the generic magic icon:
(Acid Arrow is an "old" scroll, Knock and Hold Person were made after this commit).
In the long run, is there a reason not to include the entire spell object as a property of the scroll? That way the original spell's ID and other properties could be accessed via the scroll item.
> fix scroll icon appearing on spells learned from scrolls

- RELEASE_NOTES.md
- system/src/apps/CharacterGeneratorSD.mjs
This would mostly impact custom classes as:
- There are no examples of fixed language classes in the core rules.
- One example in Unnatural Selection
- many examples in cursed scrolls
> fixes #718 where fixed ancestry languages were being overwritten by fixed class languages

- data/packs/spells.db/cloud_kill__ssnOQiOeqkdVPHn3.json
- data/packs/spells.db/fireball__j2gvzfnMGQwxqgGg.json
- data/packs/spells.db/lightning_bolt__7uTblEDfklCO1et7.json
Fireball, lightning bolt, and cloud kill are missing associated roll macros for damage.
Thanks for your work!
> Add roll macro to spells missing it

- system/src/sheets/PlayerSheetSD.mjs
The function that handles the drag drop of light spells accidently got removed in 2.0.0
> fixes #758 light spell

- system/system.json
It looks like the description for the Shadowdark system never worked right because of a typo. In v12 this also cases a warning. Fix the typo and the description pops up when you hover over the system card in the Foundry interface.
> Partial fix for #809: Fix description typo

- system/system.json
Fix issue #809 by adding grid.distance and grid.units. We need to keep gridDistance and gridUnits for v11 support, though.
> Griddistance warning fix

- RELEASE_NOTES.md
- system/src/documents/ActorSD.mjs
- system/src/documents/ItemSD.mjs
- system/src/sheets/ActorSheetSD.mjs
- system/templates/actors/player/abilities/attacks.hbs
- system/templates/chat/item-card.hbs
- system/templates/partials/weapon-attack.hbs
[#832] Melee weapons with the Thrown property now rolling correctly when used as ranged
> Implemented ranged bonuses on melee thrown weapons

- data/packs/monsters.db/life_drain__FmrC0mHGUBAGpc5P.json
- data/packs/monsters.db/poison_web__8ITOtBo5399EG3Fl.json
- system/src/dice/RollSD.mjs
- system/templates/chat/item-card.hbs
- system/templates/partials/npc-special-attack.hbs
bug fix:
[#757] NPC special attacks with an attack bonus set will now roll for attack
> Implemented rolls for NPC special attacks

- i18n/en.yaml
- system/shadowdark.mjs
- system/src/apps/EffectPanelSD.mjs
- system/src/sheets/ItemSheetSD.mjs
- system/templates/apps/effect-panel.hbs
Drop Legacy Active Effect Transferal method, and moves to the now default way of managing Active Effects on items.
Release notes:
[693] Changes made to active effects on actors will now take effects immediately
[332] implemented v11 method of working with Active Effects
> Active Effects improvements

- system/assets/mappings/map-shadowdarkling.json
Release notes
*[#983] Fixed a bug when importing "+1 to melee and range attacks" talent from shadowdarklings.
> fixes #983 - Shadowdarkling bug

- RELEASE_NOTES.md
- system/src/apps/ShadowdarklingImporterSD.mjs
A line of code that sets class was erroneously removed in this commit: https://github.com/Muttley/foundryvtt-shadowdark/commit/335f2e17ade03212935be1277dee9cb4364e7160#diff-6e97c6c9c82ded32fbadb2ed5e2510488b35e29cbcbf83c434533ad125f8f1bdL385
> Fixes #995 Character class not importing from shadowdarklings

- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/ko.yaml
- i18n/pt_BR.yaml
- i18n/ru.yaml
- i18n/sv.yaml
- scss/base/_components.scss
- system/src/dice/RollSD.mjs
- system/src/sheets/NpcSheetSD.mjs
- system/src/sheets/PlayerSheetSD.mjs
- system/templates/actors/npc/spells.hbs
- system/templates/actors/player/spells.hbs
- system/templates/chat/item-card.hbs
There was a [message in the discord](https://discordapp.com/channels/558029475837902851/1119133303514071090/1356773996011589722) asking about adding spell focus rolls so that the spell checks could be rolled without forcing the loss of a spell on a failed focus check. This PR adds a button to both PC and NPC sheets to do that. 
Considerations:
- Critical failures still result in the loss of a spell (as per rules-as-written)
- This code works primarily by hooking into pre-existing functions to cast spells, with minor changes in logic if it is a focus roll. I did this to reduce code duplication, but let me know if the preference would be for brand new functions. 
*Note that the button only appears on spells with a duration of "Focus"*
*A successful spell focus check*
*A failed spell focus …
> Add ability to easily roll spell focus checks

- system/src/chat/hooks.mjs
Fixes #1039 
When the change from "versatile" damage to "1handed" vs "2handed" damage happened (df2c3bef28558530ec6200cbed5a76faea429c13), the check for whether to display the "apply damage" button wasn't updated, so it only worked for monsters (who didn't have the change away from `primaryDamage`). 
This PR just updates the check so that either type of damage satisfies (either `damage` or `primaryDamage`)
> Fix "Apply Damage" and "Apply Healing" buttons not appearing 

- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/ko.yaml
- i18n/pt_BR.yaml
- i18n/ru.yaml
- i18n/sv.yaml
- system/src/chat/hooks.mjs
- system/src/dice/RollSD.mjs
- system/src/documents/ActorSD.mjs
- system/src/hooks.mjs
- system/src/hooks/targeting.mjs
- system/src/settings.mjs
- system/src/sheets/ActorSheetSD.mjs
This intends to fix #897. 
It doesn't apply damage automatically, however it will tell you whether you hit your target or not. 
Considerations:
- If multiple targets are selected, it will roll multiple attacks. This is so that the GM can do multiple attacks at once. Players are not able to select multiple targets.
- I've not yet worked out how to not roll the damage if the attack fails. This seems like it would ultimately be the ideal outcome, but I think this PR provides an incremental improvement without it either way. 
*Note that in the targeted example, the target is named, and the success/failure VS their AC 
is given, but the actual AC is not*
*The new "Enable Attack Targeting" setting*
> Targeting for weapon attacks

- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/ko.yaml
- i18n/pt_BR.yaml
- i18n/ru.yaml
- i18n/sv.yaml
- scss/base/_dialog.scss
- system/src/chat/hooks.mjs
- system/src/dice/RollSD.mjs
- system/src/documents/ActorSD.mjs
- system/src/macro.mjs
- system/templates/chat/item-card.hbs
- system/templates/dialog/roll-item-dialog.hbs
Adds a radio selection menu to the roll dialog for versatile weapons to choose 1H or 2H.
Adds back the "split" damage card, which is only presented if a versatile weapon is used without specifying the attack's handedness (e.g. from the macro bar). This makes the system more robust to future UI changes or third-party modules that access the rollAttack() function. 
Allows fast forwarding of macros by shift-clicking.
Fixes #1047.
> Adds handedness to roll dialog and make versatile weapon rolls more robust

- i18n/de.yaml
- i18n/en.yaml
- i18n/es.yaml
- i18n/fi.yaml
- i18n/fr.yaml
- i18n/ko.yaml
- i18n/pt_BR.yaml
- i18n/ru.yaml
- i18n/sv.yaml
- system/templates/actors/npc/spells.hbs
- system/templates/ui/sd-apps-buttons.hbs
Fixes #1038
Localizes headings in NPC spells tab. and the "Create, Import" buttons in the sidebar.
Also fixes a few ES translations that were either inconsistent with other translated phrases or were inappropriate for their intended contexts
> Localizes npc spells tab and character creator sidebar menu

- data/packs/spells.db/alarm__dBBfp7KpHXBcSEjg.json
Removes the repeated paragraph in the description of the Alarm spell.
Addresses issue Muttley/foundryvtt-shadowdark#1130.
> Remove repeated description in Alarm spell

- data/packs/class-abilities.db/demonic_possession__dsFmHTTuERiQePky.json
- data/packs/monsters.db/ambush__MCM2UX1jwTiz6Af0.json
- data/packs/monsters.db/bewilder__3tGrbD7V4Kzh69WJ.json
- data/packs/monsters.db/camouflage__pFMLvvf8uJ0g1g3S.json
- data/packs/monsters.db/deathtouch__wis_spell___decpoSp0qogWhTIt.json
- data/packs/monsters.db/engulf__RnlzBMWYWCNLB80N.json
- data/packs/monsters.db/golem__oySxFnphWlWj2S0x.json
- data/packs/monsters.db/keen_senses__ZSuJd7G2g3jX3P6B.json
- data/packs/monsters.db/life_drain__jhamHxRRpeqem41U.json
- data/packs/monsters.db/rubbery__tksSsqnnEL96jIKF.json
- data/packs/monsters.db/slow__WCgeRKkVzpcLQ4h9.json
- data/packs/monsters.db/stone_meld__MJOkTSVNf817bqhs.json
- data/packs/monsters.db/toxin__jjIo6W6eWnU2jog0.json
- data/packs/properties.db/sundering__Op1yKvM7uq5pdopr.json
- data/packs/properties.db/sundering__bAzl6RH1PW95ZkFE.json
- data/packs/quickstart-adventures.db/the_lost_citadel_of_the_scarlet_minotaur__0qbqDCsioL4HWVvW.json
- data/packs/spell-effects.db/spell_effect__blind__SOkcvkzrGMGQKhmk.json
- data/packs/spell-effects.db/spell_effect__bogboil__VOx6yLlQ23XwVvuG.json
- data/packs/spell-effects.db/spell_effect__charm_person__Z0YwWUGs3WYC6OGn.json
- data/packs/spell-effects.db/spell_effect__cleansing_weapon__7hKYL9hdnsvCUM9c.json
- data/packs/spell-effects.db/spell_effect__detect_magic__74WjFjHmUmLAiNGC.json
- data/packs/spell-effects.db/spell_effect__protection_from_evil__H7v5Izebo8O45DXB.json
- data/packs/spell-effects.db/spell_effect__sleep__FrFilluk4S5VaWut.json
- data/packs/spell-effects.db/spell_effect__web__28PPFz1MYTsfPwzh.json
- data/packs/spell-effects.db/spell_effect__zone_of_truth__cL5aPfXcad9FtHoK.json
Corrects the inconsistent use of the "Signika" font in the descriptions for the armor and weapon "sundering" properties.
Addresses issue #1129.
I see that the same issue appears in quite a number of places throughout the compendiums. I'm guessing that this was either an artefact of text conversion from PDF, or of manual copy-and-pasting. Assuming it is not a deliberate choice, I'd be happy to clean all these instances out, either as part of this PR, or in separate PRs addressing the following categories. Let me know.
- Demonic possession class ability
- Numerous monsters
- Numerous spell effects
- Lost Citadel of the Scarlet Minotaur
> Correct inconsistent typography in "sundering" properties
