Muttley/foundryvtt-shadowdark

system/src/documents/__tests__/documents-actor.test.mjs, system/src/sheets/__tests__/sheets-actor.test.mjs, system/src/testing/index.mjs, system/src/testing/testUtils.mjs
Adds tests for actor sheets, also lifts over some of the mocking functions to the `testUtils`.
=> feat(test): actor sheet testing

system/src/sheets/__tests__/sheets-item.test.mjs, system/src/testing/index.mjs
Added tests base for Item Sheets.
=> chore(test): Item sheet tests

i18n/sv.yaml
Added Swedish translation of the system. Heavily based on the translation for OSE (also done by me, so would be good to have someone review this at some point).
=> feat(i18n): Swedish translation

i18n/fi.yaml
Created a Finnish version of `en.yaml`. Some words are tricky to localize into a sensible form while maintaining word length. I think these translations should be tested for any layout breaking changes.
=> 1st version of finnish localisation

system/src/sheets/__tests__/sheets-player.test.mjs, system/src/testing/index.mjs, system/src/testing/testUtils.mjs
Added tests up to what has been written for the Player sheets.
=> chore(test): player sheet tests

system/src/sheets/__tests__/sheets-actor.test.mjs, system/src/sheets/__tests__/sheets-item.test.mjs, system/src/sheets/__tests__/sheets-player.test.mjs
Removed:
- Tests for Edit button in context menu on actor sheet
Added:
- Clicking item in actor sheet opens the item sheet
- Opening gembag tests
- Selling
- Selling gems in gembag
- Selling treasure
Fixed:
- Item sheet size
=> chore(test): 

i18n/en.yaml, system/src/dice/D20RollSD.mjs, system/src/documents/ActorSD.mjs, system/src/sheets/__tests__/sheets-player.test.mjs, system/templates/dialog/roll-dialog.hbs
Added tests & dice rolling capabilities for Ability checks.
=> feat(dice): Ability checks

i18n/en.yaml, scss/sheets/_player.scss, system/src/config.mjs, system/src/dice/D20RollSD.mjs, system/src/documents/ActorSD.mjs, system/src/documents/ItemSD.mjs, system/src/sheets/ActorSheetSD.mjs, system/src/sheets/PlayerSheetSD.mjs, system/templates/actors/player/inventory.hbs, system/templates/dialog/roll-ability-check-dialog.hbs, system/templates/dialog/roll-item-dialog.hbs
Added weapon attack rolling, it does not include damage rolls yet.
=> feat(dice): Weapon attack rolling

crowdin.yml
Resolves #6 
Added crowdin configuration.
=> feat(i18n): Crowin integration #6

system/templates/items/partials/talent-active-effects.hbs
This was a borked field before, so I changed it to a text field instead of a numerical one.
=> fix(talent): Num to text input for active effects

system/src/apps/TalentTypesSD.mjs
Fixed a bug I introduced when refactoring the Active Effects. Now talents work again.
=> fix(talent): Active Effect now works again

system/src/dice/RollSD.mjs, system/src/dice/__tests__/dice.test.js, system/src/sheets/NpcSheetSD.mjs, system/templates/chat/item-card.hbs
NPC Attacks now works with the dice mechinics.
=> feat(dice): NPC Attacks

system/src/sheets/__tests__/sheets-actor.test.mjs
Updated:
- Tests the context menus correctly
=> chore(test): Updated actor sheet tests

system/src/dice/RollSD.mjs
=> fix(dice): Dice so nice integration

scss/sheets/_item.scss
Made the Magic Properties selector field visible.
=> fix(scss): magic item properties visibility

system/src/documents/ActiveEffectSD.mjs
Forgot an `if else` there!
resolves #93
=> fix(talent): fix duplicate in category

system/src/sheets/ActorSheetSD.mjs
=> fix(dice): Weapon mastery bug

system/src/documents/ItemSD.mjs, system/src/sheets/ActorSheetSD.mjs
=> fix(item): Finesse weapons #117

system/src/dice/RollSD.mjs, system/src/documents/ActorSD.mjs
=> fix(dice): backstab & weapon mastery fixes

i18n/de.yaml, i18n/fi.yaml, i18n/fr.yaml
- 100% coverage in German & Finnish
- Added French (0% coverage)
=> chore(i18n): Updates from crowdin

RELEASE_NOTES.md, system/shadowdark.mjs, system/src/apps/LightSourceTrackerSD.mjs, system/src/tours/ShadowdarkTour.mjs, system/src/tours/ShadowdarkTourLightsourceTracker.mjs, system/src/tours/_module.mjs
This adds a guided Tour to using the Lightsource Tracker, hopefully reducing the questions on it!
=> feat(tour): Lightsource Tracker

RELEASE_NOTES.md, system/src/apps/LightSourceTrackerSD.mjs, system/src/documents/ActorSD.mjs
=> fix(lightsource): item delete order & no token error fix

RELEASE_NOTES.md, i18n/de.yaml, i18n/fi.yaml, i18n/fr.yaml, i18n/sv.yaml
I'll push an updated Release Notes when the PR is submitted here.
=> feat: Updates from crowdin

RELEASE_NOTES.md, system/src/tours/ShadowdarkTourLightsourceTracker.mjs
Added finding the macro to open the ui to the tour.
resolves #231
=> feat(tour): Added macro to light-tracker tour

RELEASE_NOTES.md, system/shadowdark.mjs, system/src/tours.mjs, system/src/tours/ShadowdarkTourLightsourceTracker.mjs, system/src/tours/ShadowdarkTourPlayerRolling.mjs
Adds a guided tour for rolling on the player character sheets!
=> feat(tour): Player Sheet Rolling

system/src/tours/ShadowdarkTourPlayerRolling.mjs
Reviewed it with a clean chat and that caused troubles, so I fixed it up and found some errors. Merging this immediately.
=> fix(tour): Correction to tour

RELEASE_NOTES.md, system/src/tours.mjs, system/src/tours/ShadowdarkTourTheLostCitadel.mjs
Adds a guided tour for importing the adventure.
=> feat(tour): The Lost Citadel

RELEASE_NOTES.md, system/src/documents/ItemSD.mjs, system/src/sheets/ActorSheetSD.mjs, system/src/sheets/PlayerSheetSD.mjs, system/templates/actors/player/inventory.hbs, system/templates/actors/player/spells.hbs
resolves #70 
I was very tempted to begin refactoring the rolling mechanics when working on this, is this implementation acceptable?
=> feat(scroll): Added spell creation & casting

RELEASE_NOTES.md, i18n/de.yaml, i18n/fi.yaml, i18n/fr.yaml, i18n/sv.yaml
Adds contributions from crowdin
=> chore(i18n): New contributions from Crowdin

RELEASE_NOTES.md, system/src/sheets/NpcSheetSD.mjs, system/templates/partials/npc-feature.hbs
=> fix(sheet): Inline rolls for NPC Feature (#350)

RELEASE_NOTES.md, i18n/en.yaml, system/src/config.mjs, system/src/documents/ItemSD.mjs, system/src/sheets/ItemSheetSD.mjs
resolves #346
resolves #347
Adds some missing options for: NPC Movement, Spell Ranges & Durations.
=> feat(config): config extensions

system/src/handlebars.mjs
=> fix(apps): Effect Panel tracking rounds

RELEASE_NOTES.md, i18n/de.yaml, i18n/fi.yaml, i18n/fr.yaml, i18n/ko.yaml, i18n/sv.yaml
Keeping this in draft until I know if sonofamom wants to be credited in the release notes!
=> feat: Korean & other Crowdin contributions

system/src/sheets/PlayerSheetSD.mjs
=> fix(effect): Non Spell Advantage talent fix

CONTRIBUTING.md, RELEASE_NOTES.md, package-lock.json, package.json
Figured we'd add this to the repo instead of me having it at my local one only.
This will enable us to pack / unpack both to LevelDB and NEDB using CLI. This would make changes to our compendiums very much more convenient to work with.
=> feat(util): Added FoundryVTT CLI to dev deps

RELEASE_NOTES.md, i18n/en.yaml, scss/sheets/actors/_index.scss, scss/sheets/actors/_light.scss, system/shadowdark.mjs, system/src/apps/LightSourceTrackerSD.mjs, system/src/hooks.mjs, system/src/hooks/drop-lightsource-on-scene.mjs, system/src/hooks/light-source-tracker.mjs, system/src/sheets/LightSheetSD.mjs, system/src/sheets/PlayerSheetSD.mjs, system/src/sheets/_module.mjs, system/template.json, system/templates/actors/light.hbs, system/templates/chat/lightsource-drop.hbs
=> feat: Light Actor & Dropping lightsource on scene

system/src/dice/RollSD.mjs, system/src/documents/__tests__/documents-item-effect-predefined-effects.test.mjs, utils/javascript.mjs
Fixes some failing tests in v10 & v11. Now all tests are green over both version.
I think we need to do some manual testing too though.
=> fix: Minor test fails, fixed

i18n/de.yaml, i18n/es.yaml, i18n/fi.yaml, i18n/fr.yaml, i18n/ko.yaml, i18n/sv.yaml
=> feat: crowdin contributions

RELEASE_NOTES.md, system/system.json
=> fix: Activates new languages

RELEASE_NOTES.md, system/src/apps/EffectPanelSD.mjs, system/src/sheets/ItemSheetSD.mjs
=> fix: Effect duration updates & removal of conditions

RELEASE_NOTES.md, system/src/dice/RollSD.mjs, system/src/dice/__tests__/dice.test.mjs
=> fix: NPC Attack respects damage bonus

RELEASE_NOTES.md, system/src/apps/ShadowdarklingImporterSD.mjs, system/src/apps/__tests__/apps-shadowdarkling-importer.test.mjs
=> fix(importer): Characters with ability stat bonuses now import correctly

system/src/tours/ShadowdarkTourLightsourceTracker.mjs
This is confirmed working in both v10 and v11 now.
=> fix: v11 tours

RELEASE_NOTES.md, data/packs/talents.db/knack.json, data/packs/talents.db/knack__luck_.json, system/src/apps/ShadowdarklingImporterSD.mjs, system/src/apps/__tests__/apps-shadowdarkling-importer.test.mjs
=> feat: kobold ancestry

system/src/chat/messages.mjs, system/templates/chat/item-card.hbs
Super simple implementation of #320.
See comments for why we may want something more robust.
=> Monster attack simple

RELEASE_NOTES.md, system/src/documents/ActorSD.mjs, system/src/documents/__tests__/documents-actor.test.mjs
=> Fix: autoroll npc hp

RELEASE_NOTES.md, system/src/sheets/ItemSheetSD.mjs, system/src/sheets/__tests__/sheets-item.test.mjs
=> fix: Properly awaiting ActiveEffects to be created on Effect items

RELEASE_NOTES.md, system/src/sheets/ActorSheetSD.mjs
=> fix: Players with edit permission on actors can now get context menu

RELEASE_NOTES.md, system/src/documents/ActorSD.mjs, system/src/documents/__tests__/documents-actor.test.mjs
=> fix: autroll npc hp correctly applies

system/src/documents/__tests__/documents-actor.test.mjs
Test was written to be inside the #450 tests instead of independent, fixed that in this commit.
=> Fixed test level for #466 tests

RELEASE_NOTES.md, system/system.json
Version bump to fix issues with The Forge
=> Release 1.4.2

system/src/migrations/MigrationRunnerSD.mjs
=> Fixed issue with migrating compendiums

system/src/documents/ActorSD.mjs, system/src/sheets/NpcSheetSD.mjs, system/templates/actors/npc/abilities/special.hbs
Lays some ground work for rollable NPC abilities and implements a posting features to chat.
Also fixed some logic to enable a scenario where a player ability could have a roll check and limited uses.
=> enhancement #184 partly implemented

system/src/tours/ShadowdarkTourLightsourceTracker.mjs, system/src/tours/ShadowdarkTourMonsterImporter.mjs, system/src/tours/ShadowdarkTourPlayerRolling.mjs, system/src/tours/ShadowdarkTourTheLostCitadel.mjs
Additional fixes for Tours and more general clean up.
=> Fixes issue #560

RELEASE_NOTES.md, system/src/documents/ActorSD.mjs, system/src/sheets/PlayerSheetSD.mjs
https://github.com/Muttley/foundryvtt-shadowdark/issues/565
=> 565 Request: Prepare actor data automatically rather than waiting for character sheet to open.

.eslintrc.json, i18n/en.yaml, scss/sheets/items/_item.scss, system/src/config.mjs, system/src/dice/RollSD.mjs, system/src/documents/ActorSD.mjs, system/src/migrations/updates/Update_231112_1.mjs, system/src/migrations/updates/_module.mjs, system/system.json, system/templates/chat/item-card.hbs, system/templates/items/partials/npc-attack.hbs
=> 337 migrate damage bonuses to formulas

data/packs/gear.db/iron_spikes__EPndk3DPOEOSvbga.json
=> remove paragraph break from iron spikes description

RELEASE_NOTES.md, system/src/apps/MonsterImporterSD.mjs
I changed the special attacks to title case in 1.6.0 and forgot to modify this line. 🤦
=> Fixed issue #618

system/src/apps/MonsterImporterSD.mjs
=> Add dice rolls to monster ability descriptions

RELEASE_NOTES.md, i18n/en.yaml, system/src/macro.mjs, system/src/utils/UtilitySD.mjs
=> closes #620

system/src/apps/CharacterGeneratorSD.mjs
Plays the dice sound whenever a field is randomized, or whenever the randomize all button is clicked on the character generator. Addresses #713
=> Add dice sound to character generator

RELEASE_NOTES.md, system/assets/mappings/map-shadowdark.json
Update token mapping file to reflect 2.0.0 monsters from #690. Addresses #725
=> Update token mapping

RELEASE_NOTES.md, data/packs/ancestries.db/dwarf__80h0XXptGDZvGAIZ.json, data/packs/ancestries.db/elf__mpqXJtii4nj4ukKk.json, data/packs/ancestries.db/goblin__QG1lAZeLfBtXR6zh.json, data/packs/ancestries.db/half_orc__0lJ8Pj0UPsbSSUTm.json, data/packs/ancestries.db/halfling__rglUPGtBSAAG3dhK.json, data/packs/ancestries.db/human__w3gbUH2DOBxfZPHO.json, data/packs/ancestries.db/kobold__855WNm4l1T7S8akj.json, i18n/en.yaml, system/src/apps/CharacterGeneratorSD.mjs, system/src/handlebars.mjs, system/src/sheets/ItemSheetSD.mjs, system/templates/items/partials/ancestry.hbs
Changes randomization of ancestries to be in line with page 40 of the core rules.
UI improvements to the ancestry item sheet.
=> 738 weights for ancestries

RELEASE_NOTES.md, data/packs/ancestries.db/kobold__855WNm4l1T7S8akj.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.1RvsqGpyjFPC9XWW.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.21lFWr4EAaJrN4PY.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.52tEmCumwpX5RTd4.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.8MqzfRhHNkt3ZaGk.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.8ykkrYPVhYXE3YEj.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.FJEcV4yoDCfWLcw7.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.I3JuQERsvhY9HrEl.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.Ii6Yz9Owtql3lp2h.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.J15Ov1mJkgZCg4nF.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.JpJQ9biuqGNQWZYU.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.RzG4Him1q59Pgudx.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.VIdEkHBgv4y6Gj0u.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.XxJDZyDQHdrJmr4m.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.ZP0KxBOKU0FX4VOw.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.aOOVz2ApXmpELyGe.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.l3mIi4ukkXPgvQFy.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.oSFOnsFDShKT1hvn.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.tCu2xRDJljPhNVZF.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.tcKuWEf8to7wM6sl.json, data/packs/rollable-tables.db/!tables.results!swiCqIGo0Bb3sJyI.tr59AE7TrrWtmeFQ.json, data/packs/rollable-tables.db/character_names__kobold__swiCqIGo0Bb3sJyI.json
=> Added random names table and release notes

system/src/socket.mjs
fixes an issue with creating level 0 characters
=> fixes #780 - character generator bug

system/src/apps/CharacterGeneratorSD.mjs
fixes issue #858
Release notes:
[858] Character Generator now properly displaying text in Foundry v12
=> fixed async issue with Character Generator

scss/base/_components.scss, scss/sheets/_actor.scss, system/src/templates.mjs, system/templates/actors/npc/abilities/attacks.hbs, system/templates/actors/npc/abilities/features.hbs, system/templates/actors/npc/abilities/specials.hbs, system/templates/actors/player/abilities/attacks.hbs, system/templates/items/tabs/titles.hbs
Release notes
[855] Corrected minor UI bugs
=> Fixed css formatting issues, typos and errors

system/src/documents/ActorSD.mjs
Fixed #852 
release notes:
[#852] Fixed a bug where ranged attacks were not showing correct damage
Many thanks to _Cussa_ for contributing fixes in this build
=> Removed duplicate calculation

data/packs/class-abilities.db/fascinate__oCNpE6bnZjPIdOO1.json, data/packs/class-abilities.db/inspire__jg2sUC3nIAI8sT18.json, data/packs/rollable-tables.db/!tables.results!ZzffJkaIfmdPzdE7.P4U9xBHYWX7t3Pqc.json, data/packs/rollable-tables.db/!tables.results!ZzffJkaIfmdPzdE7.TeZ2bqDqyjGQm4rA.json, data/packs/rollable-tables.db/!tables.results!ZzffJkaIfmdPzdE7.gmFVDABLTgEKl2gF.json, data/packs/talents.db/improved_presence_dc__gRyFoUtbbnkwcxy9.json, data/packs/talents.db/perform__J4KYu5M32T81yE1f.json
implements #872 
release notes:
[#872] Updated Bard abilities to the definitions in the Bard and Ranger v1.3 PDF
=> Chore: update bard abilities to latest version

README.md, RELEASE_NOTES.md, i18n/en.yaml, scss/base/_chat.scss, system/src/chat/messages.mjs, system/templates/chat/welcome-message.hbs
=> README and Welcome Message Updates

system/src/apps/LightSourceTrackerSD.mjs, system/src/sheets/LightSheetSD.mjs, system/src/socket.mjs
Fixes #870 
Release notes:
[#870] Fixed a bug related to picking up dropped light sources
=> Fixed bug in dropped light sources

scss/shadowdark.scss, system/src/apps/CharacterGeneratorSD.mjs, system/templates/apps/character-generator.hbs, system/templates/apps/partials/cg-details.hbs
Implements 874
Release Notes:
[#874] Added class descriptions to the character generator
=> Minor Tweaks to the Character Generator

data/macros/solodark-oracle.js, data/packs/macros.db/solodark__open_oracle__voMfAOHKkRnozC9J.json, i18n/en.yaml, system/src/apps/SoloDarkSD.mjs, system/src/apps/_module.mjs, system/src/chat/hooks.mjs, system/templates/apps/solodark.hbs, system/templates/chat/solodark-card.hbs, system/templates/chat/solodark-prompt-card.hbs
Further Implements #854 with an Oracle App
=> Solodark app

scss/apps/_shadowdarkling-importer.scss, system/assets/mappings/map-shadowdarkling.json, system/src/apps/ShadowdarklingImporterSD.mjs, system/templates/apps/shadowdarkling-importer.hbs
Release notes:
[#894] & [#902 ] & [#903] Multiple small bug fixes within the Shadowdarkling Importer
=> Shadowdarklings bugs

RELEASE_NOTES.md, system/templates/apps/character-generator/stats.hbs
=> Fixes localization in Character Generator Stats

RELEASE_NOTES.md, data/packs/talents.db/teleport_to_familiar__iLyOJbUwWHObtBQG.json
=> 1005 witch talent effect fix

RELEASE_NOTES.md, i18n/en.yaml, system/src/settings.mjs, system/src/sheets/ItemSheetSD.mjs, system/src/sheets/PlayerSheetSD.mjs, system/templates/items/basic/_partials/light-timer.hbs
=> Torch timer improvements

RELEASE_NOTES.md, data/packs/spell-effects.db/melee_attack_roll_bonus__YWdkfrbwnxtT4nUY.json, data/packs/spell-effects.db/melee_damage_bonus__o3dQi9gdFgWhDNJg.json, data/packs/spell-effects.db/ranged_attack_roll_bonus__eoN2RYcXriSBtzDB.json, data/packs/spell-effects.db/ranged_damage_bonus__1gLcCayYRfDAAQYB.json, data/packs/spell-effects.db/spell_effect__holy_weapon__r2JNgS2474vuq9oy.json
Updated actives effects on Spell effects: Holy Weapon.
There's no easy way to limit the effects to a particular weapon so I added +1 to all attacks and damage.
=> 970 ranged holy weapon
